### ISSUE TITLE
[Bug] Partially broken on Firefox, no description box or channel banner

### ISSUE THREAD

**Issue by BloodDragooner2** [Bowserinator/hellomouse-youtube-style#1]
![Here](https://user-images.githubusercontent.com/117775945/203898196-e1208680-fb66-4f17-8d62-12259c29c2b7.png)
I thought it was my settings, but does seem a bit broken. Love the style, hope it's fixable!

**Comment by Bowserinator** [comment]
Hi, have you tried disabling the "Enable if you see 2 descriptio­n boxes" bug fix in the settings?

**Comment by BloodDragooner2** [comment]
Hi! Sorry for the wait. I just tried that, works well now!

**Comment by Bowserinator** [comment]
Glad it works! I will add a note to the README later
