### ISSUE TITLE
Any way to download this without Stylus on Firefox?

### ISSUE THREAD

**Issue by waterdrinkingfox** [Bowserinator/hellomouse-youtube-style#3]
I downloaded the extension on Brave without using Stylus. I tried the same technique on Firefox but it did not work. Is there (or will there be) a way to download this without Stylus on Firefox? Thanks.

**Comment by Bowserinator** [comment]
This repo is no longer an extension, it's just a usercss. You just need an extension that can apply usercss stylus seems to be the most supported. Is there a reason you can't install Stylus?

**Comment by waterdrinkingfox** [comment]
I am not interested in stylus as I heard there were privacy issues on the extension. Thank you for your answer anyway.
