### ISSUE TITLE
Options for 15.6 inches laptop screen

### ISSUE THREAD

**Issue by vannessqn** [Bowserinator/hellomouse-youtube-style#4]
I like the userstyle but I think this is make for 1080p big screen I have a small laptop screen so I would like more options to make thumbnails grid like 20-30% bigger and 4 instead of 5 videos on a row with Dense grid option

**Comment by Bowserinator** [comment]
Done, there's now a setting for larger thumbnails

**Comment by vannessqn** [comment]
we gang!
