### ISSUE TITLE
Video gets cut off on the right and the views and date are shifted.

### ISSUE THREAD

**Issue by StormTetris** [Bowserinator/hellomouse-youtube-style#5]
I used the Stylus version of the youtube-style, and when I have the window in fullscreen, the right portion of the video gets cut off.  In addition, the views and the video creation date are now shifted to the default YouTube style (probably due to Youtube's recent update of updating the view counts without refreshing the video).
Video cutting off:
![stylus](https://github.com/Bowserinator/hellomouse-youtube-style/assets/137055469/b68e1b48-01c0-4984-99ee-c5cb74b2a0d8)
Views and date are being shifted:
![stylus2](https://github.com/Bowserinator/hellomouse-youtube-style/assets/137055469/7aa7ca4c-3642-4623-bb8d-60d16fa4f4c2)

I think it is a new update that broke the YouTube styles, as I can use a guest account on private mode just fine, but when I log in to my account, YouTube broke the style, unfortunately.

**Comment by StormTetris** [comment]
The video being cut off still appears even when I have a guest account, but the views and date is perfectly intact. 
![image](https://github.com/Bowserinator/hellomouse-youtube-style/assets/137055469/c54edcbb-d91f-47c5-88b2-aae667bce95d)

**Comment by Bowserinator** [comment]
Thanks for the bug report! I'm on vacation rn but I'll take a look when I have the time
